"""
CA Corner — Bank & Investor Reports engine.

Generates two artefact families from live Tally/Busy data:

  1. CMA (Credit Monitoring Arrangement) — 5 RBI-format forms × 5 columns
     (2 historical audited FYs + 3 projected FYs). Bank submission ready.
       - Form II  : Operating Statement (P&L)
       - Form III : Analysis of Balance Sheet
       - Form IV  : Comparative Statement of Current Assets & Liabilities
       - Form V   : Maximum Permissible Bank Finance (MPBF)
       - Form VI  : Funds Flow Statement

  2. Investor Pitch Deck — 16-page PDF + 10-page teaser + 8-sheet XLSX,
     projected on the tenant's actual Tally revenue / GM / cash-flow.

Design contract:
  - Every output file carries the tenant's company name in a header on
    every page (`_add_header_footer` canvas hook) and the footer
    "Auto-generated by FLOWRA · <ISO timestamp> · Page X of Y".
  - The methodology page (last page of every PDF, last sheet of every
    XLSX) documents the exact derivation formula for each line item.
  - All monetary inputs are treated as INR lakhs (matches Krishna Sales
    reference CMA); the engine rounds to 2 decimals per RBI convention.
  - Pure functions — no DB imports; the route layer feeds already-scoped
    (tenant + company) data in, and takes bytes out.
"""
from __future__ import annotations

import io
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak,
    KeepTogether,
)
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

logger = logging.getLogger(__name__)

# ─── Formatting helpers ──────────────────────────────────────────────────

BRAND = "#0F1B4C"      # deep navy
ACCENT = "#2563EB"     # FLOWRA blue
SOFT = "#F1F5F9"       # slate-100 stripe
FLOWRA_TAG = "Auto-generated by FLOWRA"


def _lakhs(v: float) -> str:
    """Format as Indian lakhs — matches bank CMA layout (Rs. in Lacs)."""
    if v is None:
        return "-"
    try:
        v = float(v)
    except (TypeError, ValueError):
        return "-"
    if v == 0:
        return "-"
    return f"{v:,.2f}"


def _pct(v: float) -> str:
    if v is None:
        return "-"
    try:
        return f"{float(v):.2f}%"
    except Exception:
        return "-"


def _now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().strftime("%d-%b-%Y %H:%M IST")


# ─── Data contracts (fed by the route layer) ─────────────────────────────

@dataclass
class HistoricalFY:
    """One historical financial year, aggregated from Tally sync data.

    Values in Rs. Lacs (the FLOWRA route layer converts from raw INR).
    """
    fy_label: str                     # e.g. "2023-24"
    gross_sales: float = 0.0
    other_direct_income: float = 0.0
    net_sales: float = 0.0
    purchases: float = 0.0
    direct_wages: float = 0.0
    power_fuel: float = 0.0
    other_direct_exp: float = 0.0
    depreciation: float = 0.0
    opening_stock_fg: float = 0.0
    closing_stock_fg: float = 0.0
    sga_expenses: float = 0.0
    interest: float = 0.0
    other_non_op_income: float = 0.0
    other_non_op_expense: float = 0.0
    provision_for_tax: float = 0.0

    # Balance-sheet items @ FY-end
    bank_st_borrowings: float = 0.0
    other_st_borrowings: float = 0.0
    sundry_creditors: float = 0.0
    advances_from_customers: float = 0.0
    other_statutory_liab: float = 0.0
    tl_current_portion: float = 0.0
    other_current_liab: float = 0.0
    term_loans: float = 0.0
    unsecured_loans: float = 0.0
    other_term_liab: float = 0.0
    proprietors_capital: float = 0.0
    reserves_surplus: float = 0.0
    withdrawals: float = 0.0

    cash_bank_balance: float = 0.0
    investments_current: float = 0.0
    receivables_domestic: float = 0.0
    receivables_export: float = 0.0
    inventory_raw: float = 0.0
    inventory_wip: float = 0.0
    inventory_finished: float = 0.0
    inventory_spares: float = 0.0
    advances_to_suppliers: float = 0.0
    advance_tax: float = 0.0
    other_current_assets: float = 0.0

    gross_block: float = 0.0
    accumulated_depreciation: float = 0.0
    other_non_current_assets: float = 0.0
    intangibles: float = 0.0


@dataclass
class Assumptions:
    """10 assumption inputs the user (useradmin) provides. Encrypted at
    rest in the `ca_report_assumptions` collection."""
    sales_growth_y1: float = 10.0     # % over last historical FY
    sales_growth_y2: float = 10.0
    sales_growth_y3: float = 10.0
    debtor_days_target: float = 60.0
    creditor_days_target: float = 45.0
    inventory_days_target: float = 60.0
    gp_margin_target_pct: float = 18.0
    planned_capex_y1: float = 0.0
    planned_capex_y2: float = 0.0
    planned_capex_y3: float = 0.0
    term_loan_repayment_y1: float = 0.0
    term_loan_repayment_y2: float = 0.0
    term_loan_repayment_y3: float = 0.0
    proposed_cc_limit: float = 0.0
    # Bank/regulatory (5 fields, sensitive → encrypted at rest)
    gstin: str = ""
    pan: str = ""
    msme_regn: str = ""
    bank_name: str = ""
    existing_cc_limit: float = 0.0


@dataclass
class CompanyMeta:
    company_name: str
    address: str = ""
    contact_person: str = ""
    prepared_for: str = "Bank submission — Working Capital renewal"


# ─── Projection engine ───────────────────────────────────────────────────

def project_future_fys(hist: List[HistoricalFY], a: Assumptions,
                        n_future: int = 3) -> List[HistoricalFY]:
    """Take the last historical FY and generate n_future projected FYs
    using the user assumptions + historical ratios where the user did not
    override them.

    Formulas (documented on the methodology page of each output):
      Net Sales_{y+n}  = Net Sales_y × ∏(1 + growth_i%)
      Gross Sales_{y+n} = Net Sales_{y+n} × (Gross/Net)_hist_avg
      Purchases_{y+n}  = Net Sales_{y+n} × (Purchases/Net Sales)_hist_avg
                          — reduced pro-rata to hit gp_margin_target_pct
      Sundry Debtors   = Net Sales × debtor_days_target / 365
      Sundry Creditors = Purchases × creditor_days_target / 365
      Inventory FG     = Cost of Sales × inventory_days_target / 365
      Term Loans       = prior_TL − term_loan_repayment_i
      Gross Block      = prior_GB + planned_capex_i
      Reserves         = prior_reserves + Net Profit_i − withdrawals_i
      Bank ST borrow.  = ANCHOR to Actual MPBF result of Form V (feedback
                          from the Form V computation, capped at proposed
                          CC limit if user specified).
    """
    if not hist:
        return []
    last = hist[-1]
    hist_ratios = _fit_ratios(hist)
    growths = [a.sales_growth_y1, a.sales_growth_y2, a.sales_growth_y3]
    capex = [a.planned_capex_y1, a.planned_capex_y2, a.planned_capex_y3]
    tl_paydown = [a.term_loan_repayment_y1, a.term_loan_repayment_y2,
                   a.term_loan_repayment_y3]
    out: List[HistoricalFY] = []
    prior = last
    for i in range(min(n_future, 3)):
        g = growths[i] / 100.0
        fy_label = _next_fy(prior.fy_label)
        ns = round(prior.net_sales * (1 + g), 2)
        gs_ratio = hist_ratios["gross_over_net"]
        gs = round(ns * gs_ratio, 2)

        # Cost side — target GP margin overrides historical ratio if user set it
        gp = a.gp_margin_target_pct / 100.0
        cogs_target = ns * (1 - gp)
        pur_ratio = hist_ratios["pur_over_cogs"]
        wages_ratio = hist_ratios["wages_over_cogs"]
        power_ratio = hist_ratios["power_over_cogs"]
        dexp_ratio = hist_ratios["dexp_over_cogs"]
        dep_ratio = hist_ratios["dep_over_ns"]
        sga_ratio = hist_ratios["sga_over_ns"]
        int_ratio = hist_ratios["int_over_ns"]

        purchases = round(cogs_target * pur_ratio, 2)
        wages = round(cogs_target * wages_ratio, 2)
        power = round(cogs_target * power_ratio, 2)
        dexp = round(cogs_target * dexp_ratio, 2)
        dep = round(ns * dep_ratio, 2)
        sga = round(ns * sga_ratio, 2)
        interest = round(ns * int_ratio, 2)

        opening_fg = prior.closing_stock_fg
        cost_of_sales = purchases + wages + power + dexp + dep + opening_fg
        # target FG inventory in days
        closing_fg = round((cost_of_sales * a.inventory_days_target / 365), 2)
        cost_of_sales_net = cost_of_sales - closing_fg

        pbt = ns - cost_of_sales_net - sga - interest
        tax = round(max(pbt, 0) * 0.25, 2)   # heuristic 25% tax; user can override
        np_after_tax = pbt - tax

        # Balance sheet projections
        debtors_d = round(ns * a.debtor_days_target / 365, 2)
        creditors_c = round(purchases * a.creditor_days_target / 365, 2)
        inv_raw = round(purchases * a.inventory_days_target / 365 * 0.5, 2)
        inv_wip = round(cost_of_sales_net * a.inventory_days_target / 365
                         * 0.2, 2)
        inv_fg = closing_fg
        inv_spares = prior.inventory_spares

        term_loans = max(prior.term_loans - tl_paydown[i], 0)
        gross_block = prior.gross_block + capex[i]
        accum_dep = prior.accumulated_depreciation + dep
        reserves = prior.reserves_surplus + np_after_tax - prior.withdrawals

        # Bank ST borrowing capped at proposed CC limit (if any)
        proj_bank = (a.proposed_cc_limit
                     if a.proposed_cc_limit > 0
                     else prior.bank_st_borrowings)

        out.append(HistoricalFY(
            fy_label=fy_label,
            gross_sales=gs,
            other_direct_income=prior.other_direct_income * (1 + g),
            net_sales=ns,
            purchases=purchases,
            direct_wages=wages,
            power_fuel=power,
            other_direct_exp=dexp,
            depreciation=dep,
            opening_stock_fg=opening_fg,
            closing_stock_fg=closing_fg,
            sga_expenses=sga,
            interest=interest,
            other_non_op_income=prior.other_non_op_income,
            other_non_op_expense=prior.other_non_op_expense,
            provision_for_tax=tax,
            bank_st_borrowings=proj_bank,
            other_st_borrowings=prior.other_st_borrowings,
            sundry_creditors=creditors_c,
            advances_from_customers=prior.advances_from_customers,
            other_statutory_liab=prior.other_statutory_liab,
            tl_current_portion=min(term_loans, tl_paydown[i] * 1.0),
            other_current_liab=prior.other_current_liab,
            term_loans=term_loans,
            unsecured_loans=prior.unsecured_loans,
            other_term_liab=prior.other_term_liab,
            proprietors_capital=prior.proprietors_capital,
            reserves_surplus=reserves,
            withdrawals=prior.withdrawals,
            cash_bank_balance=prior.cash_bank_balance,
            investments_current=prior.investments_current,
            receivables_domestic=debtors_d,
            receivables_export=prior.receivables_export,
            inventory_raw=inv_raw,
            inventory_wip=inv_wip,
            inventory_finished=inv_fg,
            inventory_spares=inv_spares,
            advances_to_suppliers=prior.advances_to_suppliers,
            advance_tax=prior.advance_tax,
            other_current_assets=prior.other_current_assets,
            gross_block=gross_block,
            accumulated_depreciation=accum_dep,
            other_non_current_assets=prior.other_non_current_assets,
            intangibles=prior.intangibles,
        ))
        prior = out[-1]
    return out


def _fit_ratios(hist: List[HistoricalFY]) -> Dict[str, float]:
    """Compute average historical ratios used as projection defaults."""
    def _safe_avg(nums, dens):
        pairs = [(n, d) for n, d in zip(nums, dens) if d and d != 0]
        if not pairs:
            return 0.0
        return sum(n / d for n, d in pairs) / len(pairs)
    ns = [h.net_sales for h in hist]
    gs = [h.gross_sales for h in hist]
    cogs = [h.purchases + h.direct_wages + h.power_fuel + h.other_direct_exp
             for h in hist]
    return {
        "gross_over_net":  _safe_avg(gs, ns) or 1.0,
        "pur_over_cogs":   _safe_avg([h.purchases for h in hist], cogs) or 0.8,
        "wages_over_cogs": _safe_avg([h.direct_wages for h in hist], cogs) or 0.05,
        "power_over_cogs": _safe_avg([h.power_fuel for h in hist], cogs) or 0.02,
        "dexp_over_cogs":  _safe_avg([h.other_direct_exp for h in hist], cogs) or 0.03,
        "dep_over_ns":     _safe_avg([h.depreciation for h in hist], ns) or 0.01,
        "sga_over_ns":     _safe_avg([h.sga_expenses for h in hist], ns) or 0.05,
        "int_over_ns":     _safe_avg([h.interest for h in hist], ns) or 0.01,
    }


def _next_fy(label: str) -> str:
    """'2023-24' → '2024-25'."""
    try:
        a, b = label.split("-")
        na = int(a) + 1
        nb = str(int(b) + 1).zfill(2)
        return f"{na}-{nb}"
    except Exception:
        return "Next FY"


# ─── Derived aggregates the forms need ───────────────────────────────────

def compute_form_ii(fy: HistoricalFY) -> Dict[str, float]:
    """Form II — Operating Statement derived totals."""
    cost_of_prod = (fy.purchases + fy.direct_wages + fy.power_fuel
                     + fy.other_direct_exp + fy.depreciation)
    cost_of_sales = cost_of_prod + fy.opening_stock_fg - fy.closing_stock_fg
    total_cost = cost_of_sales + fy.sga_expenses
    op_profit_bi = fy.net_sales - total_cost
    op_profit_ai = op_profit_bi - fy.interest
    non_op_net = fy.other_non_op_income - fy.other_non_op_expense
    pbt = op_profit_ai + non_op_net
    npat = pbt - fy.provision_for_tax
    return {
        "cost_of_production": cost_of_prod,
        "cost_of_sales": cost_of_sales,
        "total_cost": total_cost,
        "op_profit_bi": op_profit_bi,
        "op_profit_ai": op_profit_ai,
        "non_op_net": non_op_net,
        "pbt": pbt,
        "npat": npat,
    }


def compute_form_iii(fy: HistoricalFY) -> Dict[str, float]:
    """Form III — Balance Sheet Analysis derived totals + ratios."""
    tcl = (fy.bank_st_borrowings + fy.other_st_borrowings + fy.sundry_creditors
            + fy.advances_from_customers + fy.other_statutory_liab
            + fy.tl_current_portion + fy.other_current_liab)
    ttl = fy.term_loans + fy.unsecured_loans + fy.other_term_liab
    tol = tcl + ttl
    nw = (fy.proprietors_capital + fy.reserves_surplus - fy.withdrawals)
    tnw = nw - fy.intangibles
    tca = (fy.cash_bank_balance + fy.investments_current
            + fy.receivables_domestic + fy.receivables_export
            + fy.inventory_raw + fy.inventory_wip + fy.inventory_finished
            + fy.inventory_spares + fy.advances_to_suppliers
            + fy.advance_tax + fy.other_current_assets)
    net_block = fy.gross_block - fy.accumulated_depreciation
    total_assets = (tca + net_block + fy.other_non_current_assets
                     + fy.intangibles)
    nwc = tca - tcl
    current_ratio = (tca / tcl) if tcl > 0 else 0
    tol_tnw = (tol / tnw) if tnw > 0 else 0
    ttl_tnw = (ttl / tnw) if tnw > 0 else 0
    return {
        "tcl": tcl, "ttl": ttl, "tol": tol, "nw": nw, "tnw": tnw,
        "tca": tca, "net_block": net_block, "total_assets": total_assets,
        "nwc": nwc, "current_ratio": current_ratio,
        "tol_tnw": tol_tnw, "ttl_tnw": ttl_tnw,
    }


def compute_form_v_mpbf(fy: HistoricalFY, other_cl_excl_bank: float,
                         projected_nwc: float) -> Dict[str, float]:
    """Form V — Maximum Permissible Bank Finance (both methods)."""
    d3 = compute_form_iii(fy)
    tca = d3["tca"]
    ocl = other_cl_excl_bank
    wcg = tca - ocl
    # Method 1: min NWC = 25% of WCG
    m1_min_nwc = 0.25 * wcg
    m1_a = wcg - m1_min_nwc
    m1_b = wcg - projected_nwc
    m1_mpbf = min(m1_a, m1_b)
    m1_shortfall = max(m1_min_nwc - projected_nwc, 0)
    # Method 2: min NWC = 25% of TCA
    m2_min_nwc = 0.25 * tca
    m2_a = wcg - m2_min_nwc
    m2_b = wcg - projected_nwc
    m2_mpbf = min(m2_a, m2_b)
    m2_shortfall = max(m2_min_nwc - projected_nwc, 0)
    return {
        "tca": tca, "ocl": ocl, "wcg": wcg,
        "m1_min_nwc": m1_min_nwc, "m1_a": m1_a, "m1_b": m1_b,
        "m1_mpbf": max(m1_mpbf, 0), "m1_shortfall": m1_shortfall,
        "m2_min_nwc": m2_min_nwc, "m2_a": m2_a, "m2_b": m2_b,
        "m2_mpbf": max(m2_mpbf, 0), "m2_shortfall": m2_shortfall,
    }


# ─── PDF generation utilities ────────────────────────────────────────────

def _make_canvas_stamper(company_name: str, doc_title: str):
    """Returns an on-page callback that stamps company name (header) and
    'Auto-generated by FLOWRA · timestamp · Page X of Y' (footer) on every
    page — user's mandatory branding requirement."""
    ts = _now_iso()

    def _on_page(canvas, doc):
        canvas.saveState()
        w, h = A4 if doc.pagesize == A4 else doc.pagesize
        # Header
        canvas.setFillColor(colors.HexColor(BRAND))
        canvas.setFont("Helvetica-Bold", 10)
        canvas.drawString(1.2 * cm, h - 0.9 * cm, company_name)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748B"))
        canvas.drawRightString(w - 1.2 * cm, h - 0.9 * cm, doc_title)
        canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
        canvas.line(1.2 * cm, h - 1.1 * cm, w - 1.2 * cm, h - 1.1 * cm)
        # Footer
        canvas.setFont("Helvetica-Oblique", 7)
        canvas.setFillColor(colors.HexColor("#94A3B8"))
        footer = f"{FLOWRA_TAG}  ·  {ts}  ·  Page {doc.page}"
        canvas.drawString(1.2 * cm, 0.7 * cm, footer)
        canvas.setFillColor(colors.HexColor(ACCENT))
        canvas.setFont("Helvetica-Bold", 7)
        canvas.drawRightString(w - 1.2 * cm, 0.7 * cm, "flowralive.in")
        canvas.restoreState()
    return _on_page


def _para(text: str, style: str = "body") -> Paragraph:
    styles = getSampleStyleSheet()
    if style == "h1":
        p = ParagraphStyle("h1", parent=styles["Title"], fontSize=16,
                            textColor=colors.HexColor(BRAND),
                            spaceAfter=6)
    elif style == "h2":
        p = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=11,
                            textColor=colors.HexColor(BRAND),
                            spaceBefore=8, spaceAfter=4)
    elif style == "small":
        p = ParagraphStyle("small", parent=styles["BodyText"], fontSize=7,
                            textColor=colors.HexColor("#64748B"),
                            leading=9)
    elif style == "note":
        p = ParagraphStyle("note", parent=styles["BodyText"], fontSize=8,
                            textColor=colors.HexColor("#475569"),
                            leading=11, italic=True)
    else:
        p = ParagraphStyle("body", parent=styles["BodyText"], fontSize=9,
                            leading=12)
    return Paragraph(text, p)


def _form_table(rows: List[List[Any]], col_widths: List[float],
                 headers: List[str], highlight_rows: Optional[List[int]] = None
                 ) -> Table:
    highlight_rows = highlight_rows or []
    # Guard: clamp indices to the actual body length so out-of-range hints
    # (which can happen if a form has fewer rows in a particular tenant)
    # don't crash ReportLab's row-background painter.
    n_body = len(rows)
    highlight_rows = [r for r in highlight_rows if 0 <= r < n_body]
    data = [headers] + rows
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(BRAND)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor(BRAND)),
        ("GRID", (0, 1), (-1, -1), 0.15, colors.HexColor("#E2E8F0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.white, colors.HexColor(SOFT)]),
    ]
    for r in highlight_rows:
        style.append(("BACKGROUND", (0, r + 1), (-1, r + 1),
                      colors.HexColor("#DBEAFE")))
        style.append(("FONTNAME", (0, r + 1), (-1, r + 1), "Helvetica-Bold"))
    t.setStyle(TableStyle(style))
    return t


def _column_headers_for_fys(all_fys: List[HistoricalFY], n_hist: int
                              ) -> List[str]:
    """Match the bank CMA convention: '2021-22 Actual (1)',
    '2023-24 Estimated (3)', '2024-25 Projections (4)'."""
    labels = []
    for i, fy in enumerate(all_fys):
        if i < n_hist - 1:
            tag = "Actual"
        elif i == n_hist - 1:
            tag = "Estimated"
        else:
            tag = "Projections"
        labels.append(f"{fy.fy_label}\n{tag} ({i + 1})")
    return labels


# ─── CMA PDF builder ─────────────────────────────────────────────────────

def build_cma_pdf(meta: CompanyMeta, hist: List[HistoricalFY],
                   proj: List[HistoricalFY], a: Assumptions) -> bytes:
    """Generate the 5-form CMA report as a PDF."""
    all_fys = hist + proj
    n_hist = len(hist)
    col_labels = _column_headers_for_fys(all_fys, n_hist)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=1.2 * cm, rightMargin=1.2 * cm,
        topMargin=1.6 * cm, bottomMargin=1.2 * cm,
        title=f"CMA — {meta.company_name}",
    )
    story: List[Any] = []

    # ── Cover page ──
    story.append(_para(
        f"CMA Report — {meta.company_name}", "h1"))
    story.append(_para(
        f"Credit Monitoring Arrangement · Prepared for: {meta.prepared_for}",
        "small"))
    story.append(Spacer(1, 8))
    fys_range = (f"{hist[0].fy_label} to {proj[-1].fy_label}"
                  if hist and proj else "-")
    cover = [
        ["Company", meta.company_name],
        ["Address", meta.address or "-"],
        ["Bank", a.bank_name or "-"],
        ["GSTIN", a.gstin or "-"],
        ["PAN", a.pan or "-"],
        ["MSME Registration", a.msme_regn or "-"],
        ["Existing CC / OD limit (₹ Lacs)", _lakhs(a.existing_cc_limit)],
        ["Proposed CC / OD limit (₹ Lacs)", _lakhs(a.proposed_cc_limit)],
        ["Financial years covered", fys_range],
        ["Historical FYs (Tally-derived)", str(n_hist)],
        ["Projection FYs", str(len(proj))],
        ["Report generated on", _now_iso()],
    ]
    t = Table(cover, colWidths=[6 * cm, 10 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor(SOFT)),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#F1F5F9")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))
    story.append(_para(
        "This report was generated automatically by FLOWRA from the "
        "company's Tally / Busy sync data. Historical figures come "
        "directly from ledger balances and voucher aggregates. Projected "
        "figures were computed using the assumptions on the last page of "
        "this document; the CA / promoter may edit any assumption and "
        "re-generate this report at any time from the CA Corner tab.",
        "note"))
    story.append(PageBreak())

    # ── Form II ──
    story.append(_para("FORM II — Operating Statement", "h1"))
    story.append(_para("All figures in Rs. Lacs unless stated otherwise.",
                        "small"))
    story.append(Spacer(1, 4))
    form_ii = [_form_ii_rows(fy) for fy in all_fys]
    ii_col_widths = [7.6 * cm] + [2 * cm] * len(all_fys)
    ii_rows = _transpose_rows(form_ii, _form_ii_labels())
    story.append(_form_table(ii_rows, ii_col_widths,
                              [""] + col_labels,
                              highlight_rows=[2, 8, 11, 14, 16, 20]))
    story.append(PageBreak())

    # ── Form III ──
    story.append(_para("FORM III — Analysis of Balance Sheet", "h1"))
    form_iii = [_form_iii_rows(fy) for fy in all_fys]
    iii_col_widths = [7.6 * cm] + [2 * cm] * len(all_fys)
    iii_rows = _transpose_rows(form_iii, _form_iii_labels())
    story.append(_form_table(iii_rows, iii_col_widths,
                              [""] + col_labels,
                              highlight_rows=[9, 16, 17, 22, 43, 44,
                                               45, 46, 47]))
    story.append(PageBreak())

    # ── Form IV — Comparative CA/CL ──
    story.append(_para("FORM IV — Comparative Statement of Current "
                         "Assets & Current Liabilities", "h1"))
    form_iv = [_form_iv_rows(fy) for fy in all_fys]
    iv_col_widths = [7.6 * cm] + [2 * cm] * len(all_fys)
    iv_rows = _transpose_rows(form_iv, _form_iv_labels())
    story.append(_form_table(iv_rows, iv_col_widths,
                              [""] + col_labels,
                              highlight_rows=[8, 15]))
    story.append(PageBreak())

    # ── Form V — MPBF ──
    story.append(_para(
        "FORM V — Computation of Maximum Permissible Bank Finance", "h1"))
    story.append(_para(
        "Both methods computed per RBI Tandon Committee guidelines. Bank "
        "typically adopts the LOWER of Method 1 and Method 2.", "note"))
    story.append(Spacer(1, 4))
    form_v = [_form_v_rows(fy) for fy in all_fys]
    v_col_widths = [7.6 * cm] + [2 * cm] * len(all_fys)
    v_rows = _transpose_rows(form_v, _form_v_labels())
    story.append(_form_table(v_rows, v_col_widths,
                              [""] + col_labels,
                              highlight_rows=[7, 16]))
    story.append(PageBreak())

    # ── Form VI — Funds Flow ──
    story.append(_para("FORM VI — Funds Flow Statement", "h1"))
    ff_pairs = _funds_flow_deltas(all_fys)
    ff_col_labels = ["Movement " + f"{a.fy_label}→{b.fy_label}"
                      for a, b in zip(all_fys[:-1], all_fys[1:])]
    ff_col_widths = [7.6 * cm] + [2.5 * cm] * len(ff_col_labels)
    ff_rows = _transpose_rows(ff_pairs, _funds_flow_labels())
    story.append(_form_table(ff_rows, ff_col_widths,
                              [""] + ff_col_labels,
                              highlight_rows=[7, 15]))
    story.append(PageBreak())

    # ── Methodology page ──
    story.append(_para("Methodology & Data Sources", "h1"))
    for section, body in _methodology_blocks():
        story.append(_para(section, "h2"))
        story.append(_para(body, "body"))
        story.append(Spacer(1, 4))
    story.append(Spacer(1, 6))
    story.append(_para(
        "<b>Assumptions used in this projection</b>", "h2"))
    a_rows = [
        ["Sales growth Y1 / Y2 / Y3 (%)",
         f"{a.sales_growth_y1} / {a.sales_growth_y2} / {a.sales_growth_y3}"],
        ["Debtor days (target)", str(a.debtor_days_target)],
        ["Creditor days (target)", str(a.creditor_days_target)],
        ["Inventory days (target)", str(a.inventory_days_target)],
        ["Gross Profit margin target (%)", str(a.gp_margin_target_pct)],
        ["Planned capex Y1 / Y2 / Y3 (₹ Lacs)",
         f"{a.planned_capex_y1} / {a.planned_capex_y2} / {a.planned_capex_y3}"],
        ["Term-loan paydown Y1 / Y2 / Y3 (₹ Lacs)",
         f"{a.term_loan_repayment_y1} / {a.term_loan_repayment_y2} / "
         f"{a.term_loan_repayment_y3}"],
        ["Proposed CC/OD limit (₹ Lacs)", _lakhs(a.proposed_cc_limit)],
    ]
    at = Table(a_rows, colWidths=[9 * cm, 7 * cm])
    at.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor(SOFT)),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.2, colors.HexColor("#E2E8F0")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(at)

    doc.build(story,
               onFirstPage=_make_canvas_stamper(meta.company_name,
                                                  "CMA Report"),
               onLaterPages=_make_canvas_stamper(meta.company_name,
                                                  "CMA Report"))
    return buf.getvalue()


# ─── Row builders — Form II ──────────────────────────────────────────────

_FORM_II_LABELS = [
    "1. Gross Sales",
    "   (i) Domestic Sales",
    "   (ii) Other Direct Income",
    "3. Net Sales",
    "4. %age rise / fall in net sales",
    "5(i). Purchases (Indigenous)",
    "5(iii). Direct labour & wages",
    "5(iv). Power & Fuels",
    "5(v). Other direct expenses",
    "5(vi). Depreciation",
    "5(vii). Sub-total — Cost of Production",
    "5(xi). Add: Opening stock of finished goods",
    "5(xii). Less: Closing stock of finished goods",
    "5(xiii). Sub-total — Total Cost of Sales",
    "6. Selling, General & Administrative Exp.",
    "7. Sub-total (5 + 6)",
    "8. Operating profit before interest",
    "9. Interest",
    "10. Operating profit after interest",
    "11. Net non-operating income / (expense)",
    "12. Profit before tax",
    "13. Provision for taxes",
    "14. Net Profit / (Loss)",
]


def _form_ii_labels() -> List[str]:
    return _FORM_II_LABELS


def _form_ii_rows(fy: HistoricalFY) -> List[str]:
    d = compute_form_ii(fy)
    return [
        _lakhs(fy.gross_sales),
        _lakhs(fy.gross_sales - fy.other_direct_income),
        _lakhs(fy.other_direct_income),
        _lakhs(fy.net_sales),
        "-",   # growth % filled in by caller (needs previous FY)
        _lakhs(fy.purchases),
        _lakhs(fy.direct_wages),
        _lakhs(fy.power_fuel),
        _lakhs(fy.other_direct_exp),
        _lakhs(fy.depreciation),
        _lakhs(d["cost_of_production"]),
        _lakhs(fy.opening_stock_fg),
        _lakhs(fy.closing_stock_fg),
        _lakhs(d["cost_of_sales"]),
        _lakhs(fy.sga_expenses),
        _lakhs(d["total_cost"]),
        _lakhs(d["op_profit_bi"]),
        _lakhs(fy.interest),
        _lakhs(d["op_profit_ai"]),
        _lakhs(d["non_op_net"]),
        _lakhs(d["pbt"]),
        _lakhs(fy.provision_for_tax),
        _lakhs(d["npat"]),
    ]


# ─── Row builders — Form III ─────────────────────────────────────────────

_FORM_III_LABELS = [
    "1. Short-term borrowings from banks",
    "   (i) From applicant bank",
    "   (ii) From other banks",
    "2. Short-term borrowings from others",
    "3. Sundry Creditors (Trade)",
    "4. Advances from customers / dealer deposits",
    "7. Other statutory liabilities",
    "8. Current portion of term loans",
    "9. Other current liabilities & provisions",
    "10. TOTAL CURRENT LIABILITIES",
    "13. Term Loans (long-term portion)",
    "15. Unsecured Loans (Rels. & Friends)",
    "16. Other term liabilities",
    "17. TOTAL TERM LIABILITIES",
    "18. TOTAL OUTSIDE LIABILITIES (10+17)",
    "19. Proprietor's Capital",
    "22. Other Reserves & Surplus (P&L b/f)",
    "23a. Less: Withdrawals",
    "24. NET WORTH (19+22 − 23a)",
    "26. Cash & Bank balance",
    "27. Investments (short-term)",
    "28. Receivables (Domestic)",
    "28(ii). Receivables (Export)",
    "30(i). Inventory — Raw Materials",
    "30(ii). Inventory — WIP",
    "30(iii). Inventory — Finished Goods",
    "30(iv). Inventory — Spares",
    "31. Advances to suppliers",
    "32. Advance payment of taxes",
    "33. Other current assets",
    "34. TOTAL CURRENT ASSETS",
    "35. Gross Block (Fixed Assets)",
    "36. Less: Depreciation to date",
    "37. NET BLOCK (35 − 36)",
    "41. Other non-current assets",
    "42. Intangible assets",
    "43. TOTAL ASSETS (34+37+41+42)",
    "44. TANGIBLE NET WORTH (24 − 42)",
    "45. NET WORKING CAPITAL (34 − 10)",
    "46. Current Ratio (34 / 10)",
    "47. TOL / TNW",
    "48. TTL / TNW",
]


def _form_iii_labels() -> List[str]:
    return _FORM_III_LABELS


def _form_iii_rows(fy: HistoricalFY) -> List[str]:
    d = compute_form_iii(fy)
    return [
        _lakhs(fy.bank_st_borrowings),
        _lakhs(fy.bank_st_borrowings),   # applicant bank (heuristic: all bank ST)
        "-",
        _lakhs(fy.other_st_borrowings),
        _lakhs(fy.sundry_creditors),
        _lakhs(fy.advances_from_customers),
        _lakhs(fy.other_statutory_liab),
        _lakhs(fy.tl_current_portion),
        _lakhs(fy.other_current_liab),
        _lakhs(d["tcl"]),
        _lakhs(fy.term_loans),
        _lakhs(fy.unsecured_loans),
        _lakhs(fy.other_term_liab),
        _lakhs(d["ttl"]),
        _lakhs(d["tol"]),
        _lakhs(fy.proprietors_capital),
        _lakhs(fy.reserves_surplus),
        _lakhs(fy.withdrawals),
        _lakhs(d["nw"]),
        _lakhs(fy.cash_bank_balance),
        _lakhs(fy.investments_current),
        _lakhs(fy.receivables_domestic),
        _lakhs(fy.receivables_export),
        _lakhs(fy.inventory_raw),
        _lakhs(fy.inventory_wip),
        _lakhs(fy.inventory_finished),
        _lakhs(fy.inventory_spares),
        _lakhs(fy.advances_to_suppliers),
        _lakhs(fy.advance_tax),
        _lakhs(fy.other_current_assets),
        _lakhs(d["tca"]),
        _lakhs(fy.gross_block),
        _lakhs(fy.accumulated_depreciation),
        _lakhs(d["net_block"]),
        _lakhs(fy.other_non_current_assets),
        _lakhs(fy.intangibles),
        _lakhs(d["total_assets"]),
        _lakhs(d["tnw"]),
        _lakhs(d["nwc"]),
        f"{d['current_ratio']:.2f}" if d["current_ratio"] else "-",
        f"{d['tol_tnw']:.2f}" if d["tol_tnw"] else "-",
        f"{d['ttl_tnw']:.2f}" if d["ttl_tnw"] else "-",
    ]


# ─── Row builders — Form IV (Current A + L comparative) ──────────────────

_FORM_IV_LABELS = [
    "1. Raw Materials (months' consumption)",
    "2. Other spares & fuels",
    "3. Stocks-in-process (months' COP)",
    "4. Finished goods (months' COS)",
    "5. Receivables — Domestic (months' sales)",
    "6. Receivables — Export (months' export)",
    "7. Advances to suppliers",
    "8. Other current assets incl. cash/bank",
    "9. TOTAL CURRENT ASSETS",
    "10. Creditors (months' purchases)",
    "11(a). Advances from customers",
    "11(b). Accrued expenses",
    "12. Statutory liabilities",
    "13. Other current liab. excl. bank borrowings",
    "14. TOTAL CL excl. bank borrowings",
]


def _form_iv_labels() -> List[str]:
    return _FORM_IV_LABELS


def _months(part: float, base: float) -> str:
    """part / base * 12 → 'X.Xm'. Returns '-' when base is zero."""
    if not base or base <= 0:
        return "-"
    m = part * 12 / base
    if m == 0:
        return "-"
    return f"{m:.1f}m"


def _form_iv_rows(fy: HistoricalFY) -> List[str]:
    d = compute_form_iii(fy)
    d2 = compute_form_ii(fy)
    ns = fy.net_sales or 1.0
    cop = d2["cost_of_production"] or 1.0
    cos = d2["cost_of_sales"] or 1.0
    pur = fy.purchases or 1.0
    ocl_excl_bank = (d["tcl"] - fy.bank_st_borrowings)
    return [
        f"{_lakhs(fy.inventory_raw)}  ({_months(fy.inventory_raw, pur)})",
        f"{_lakhs(fy.inventory_spares)}  ({_months(fy.inventory_spares, pur)})",
        f"{_lakhs(fy.inventory_wip)}  ({_months(fy.inventory_wip, cop)})",
        f"{_lakhs(fy.inventory_finished)}  ({_months(fy.inventory_finished, cos)})",
        f"{_lakhs(fy.receivables_domestic)}  ({_months(fy.receivables_domestic, ns)})",
        f"{_lakhs(fy.receivables_export)}  ({_months(fy.receivables_export, ns)})",
        _lakhs(fy.advances_to_suppliers),
        _lakhs(fy.cash_bank_balance + fy.investments_current
                + fy.advance_tax + fy.other_current_assets),
        _lakhs(d["tca"]),
        f"{_lakhs(fy.sundry_creditors)}  ({_months(fy.sundry_creditors, pur)})",
        _lakhs(fy.advances_from_customers),
        _lakhs(fy.other_current_liab),
        _lakhs(fy.other_statutory_liab),
        _lakhs(fy.other_st_borrowings + fy.tl_current_portion),
        _lakhs(ocl_excl_bank),
    ]


# ─── Row builders — Form V (MPBF) ────────────────────────────────────────

_FORM_V_LABELS = [
    "  --- Method 1 of Lending ---",
    "1. Total Current Assets",
    "2. Other Current Liab. (excl. bank borrowings)",
    "3. Working Capital Gap (1 − 2)",
    "4. Min. stipulated Net WC (25% of WCG)",
    "5. Actual / projected Net WC",
    "6. Item 3 − Item 4",
    "7. Item 3 − Item 5",
    "8. MPBF (lower of 6 or 7)",
    "9. Excess borrowings / shortfall (4 − 5)",
    "  --- Method 2 of Lending ---",
    "1. Total Current Assets",
    "2. Other Current Liab. (excl. bank borrowings)",
    "3. Working Capital Gap (1 − 2)",
    "4. Min. stipulated Net WC (25% of TCA)",
    "5. Actual / projected Net WC",
    "6. Item 3 − Item 4",
    "7. Item 3 − Item 5",
    "8. MPBF (lower of 6 or 7)",
    "9. Excess borrowings / shortfall (4 − 5)",
]


def _form_v_labels() -> List[str]:
    return _FORM_V_LABELS


def _form_v_rows(fy: HistoricalFY) -> List[str]:
    d = compute_form_iii(fy)
    ocl_excl_bank = d["tcl"] - fy.bank_st_borrowings
    m = compute_form_v_mpbf(fy, ocl_excl_bank, d["nwc"])
    return [
        "",
        _lakhs(m["tca"]),
        _lakhs(m["ocl"]),
        _lakhs(m["wcg"]),
        _lakhs(m["m1_min_nwc"]),
        _lakhs(d["nwc"]),
        _lakhs(m["m1_a"]),
        _lakhs(m["m1_b"]),
        _lakhs(m["m1_mpbf"]),
        _lakhs(m["m1_shortfall"]),
        "",
        _lakhs(m["tca"]),
        _lakhs(m["ocl"]),
        _lakhs(m["wcg"]),
        _lakhs(m["m2_min_nwc"]),
        _lakhs(d["nwc"]),
        _lakhs(m["m2_a"]),
        _lakhs(m["m2_b"]),
        _lakhs(m["m2_mpbf"]),
        _lakhs(m["m2_shortfall"]),
    ]


# ─── Row builders — Form VI (Funds Flow) ─────────────────────────────────

_FF_LABELS = [
    "SOURCES",
    "  a) Net Profit (before tax)",
    "  b) Depreciation",
    "  c) Increase in Capital",
    "  d) Increase in Term Liabilities",
    "  e) Decrease in Fixed Assets",
    "  f) Decrease in Other Non-current Assets",
    "TOTAL SOURCES",
    "USES",
    "  a) Net Loss",
    "  b) Decrease in Term Liabilities",
    "  c) Increase in Fixed Assets",
    "  d) Increase in Other Non-current Assets",
    "  e) Dividend / Withdrawals",
    "TOTAL USES",
    "Long-term Surplus / (Deficit)",
    "Δ Current Assets",
    "Δ Current Liab. (excl. bank borrowings)",
    "Δ Working Capital Gap",
    "Net Surplus / (Deficit)",
    "Δ Bank Borrowings (residual)",
]


def _funds_flow_labels() -> List[str]:
    return _FF_LABELS


def _funds_flow_deltas(all_fys: List[HistoricalFY]) -> List[List[str]]:
    """Compute funds-flow movement between consecutive FYs."""
    out = []
    for prev, cur in zip(all_fys[:-1], all_fys[1:]):
        pi = compute_form_ii(cur)
        p3 = compute_form_iii(prev)
        c3 = compute_form_iii(cur)
        pbt = pi["pbt"]
        dep = cur.depreciation
        d_cap = max(cur.proprietors_capital - prev.proprietors_capital, 0)
        d_tl = max((cur.term_loans + cur.unsecured_loans + cur.other_term_liab)
                    - (prev.term_loans + prev.unsecured_loans
                        + prev.other_term_liab), 0)
        d_fa_dec = max(prev.gross_block - cur.gross_block, 0)
        d_nca_dec = max(prev.other_non_current_assets
                          - cur.other_non_current_assets, 0)
        total_sources = pbt + dep + d_cap + d_tl + d_fa_dec + d_nca_dec

        net_loss = max(-pi["npat"], 0)
        dec_tl = max((prev.term_loans + prev.unsecured_loans
                       + prev.other_term_liab)
                       - (cur.term_loans + cur.unsecured_loans
                           + cur.other_term_liab), 0)
        d_fa_inc = max(cur.gross_block - prev.gross_block, 0)
        d_nca_inc = max(cur.other_non_current_assets
                          - prev.other_non_current_assets, 0)
        div_wd = cur.withdrawals
        total_uses = net_loss + dec_tl + d_fa_inc + d_nca_inc + div_wd

        lt_surplus = total_sources - total_uses
        d_ca = c3["tca"] - p3["tca"]
        d_cl_ex_bank = ((c3["tcl"] - cur.bank_st_borrowings)
                          - (p3["tcl"] - prev.bank_st_borrowings))
        d_wcg = d_ca - d_cl_ex_bank
        net_sd = lt_surplus - d_wcg
        d_bank = cur.bank_st_borrowings - prev.bank_st_borrowings

        row_dict = {
            "SOURCES": "",
            "  a) Net Profit (before tax)": _lakhs(pbt),
            "  b) Depreciation": _lakhs(dep),
            "  c) Increase in Capital": _lakhs(d_cap),
            "  d) Increase in Term Liabilities": _lakhs(d_tl),
            "  e) Decrease in Fixed Assets": _lakhs(d_fa_dec),
            "  f) Decrease in Other Non-current Assets": _lakhs(d_nca_dec),
            "TOTAL SOURCES": _lakhs(total_sources),
            "USES": "",
            "  a) Net Loss": _lakhs(net_loss),
            "  b) Decrease in Term Liabilities": _lakhs(dec_tl),
            "  c) Increase in Fixed Assets": _lakhs(d_fa_inc),
            "  d) Increase in Other Non-current Assets": _lakhs(d_nca_inc),
            "  e) Dividend / Withdrawals": _lakhs(div_wd),
            "TOTAL USES": _lakhs(total_uses),
            "Long-term Surplus / (Deficit)": _lakhs(lt_surplus),
            "Δ Current Assets": _lakhs(d_ca),
            "Δ Current Liab. (excl. bank borrowings)": _lakhs(d_cl_ex_bank),
            "Δ Working Capital Gap": _lakhs(d_wcg),
            "Net Surplus / (Deficit)": _lakhs(net_sd),
            "Δ Bank Borrowings (residual)": _lakhs(d_bank),
        }
        out.append([row_dict.get(k, "-") for k in _FF_LABELS])
    return out


def _transpose_rows(cols: List[List[Any]], labels: List[str]) -> List[List[Any]]:
    """Convert [column1_values, column2_values, ...] into rows where each
    row is [label, col1_val, col2_val, ...]. Assumes all columns are the
    same length as `labels`."""
    rows = []
    for i, label in enumerate(labels):
        row = [label]
        for col in cols:
            row.append(col[i] if i < len(col) else "-")
        rows.append(row)
    return rows


# ─── Methodology text (embedded verbatim in every generated PDF) ─────────

def _methodology_blocks() -> List[tuple]:
    return [
        ("Historical figures (columns marked 'Actual' & 'Estimated')",
         "All historical FY numbers are aggregated directly from your Tally / "
         "Busy sync data. Sales come from the sales_vouchers collection; "
         "purchases from purchase_vouchers; ledger balances (Sundry Debtors, "
         "Sundry Creditors, Bank OD, Term Loans, Capital, Reserves) from the "
         "all_ledgers collection; inventory from the stock_items collection; "
         "depreciation from the P&L expense group. NO manual data entry is "
         "involved in the historical columns — every rupee ties back to a "
         "ledger the CA / promoter can audit inside Tally."),
        ("Projections (columns marked 'Projections')",
         "Projected columns are built by applying the assumptions you entered "
         "in the Assumptions section against a base of the most recent "
         "historical FY. Growth is compounded year-on-year. Cost lines "
         "(Purchases, Wages, Power, SG&A) hold their historical ratio-to-"
         "sales unless the target GP Margin overrides them. Term loans are "
         "reduced by your planned paydown; Fixed Assets grow by your planned "
         "capex; Reserves grow by projected Net Profit − Withdrawals."),
        ("Working-capital projections",
         "Sundry Debtors = Net Sales × Debtor-days-target / 365. "
         "Sundry Creditors = Purchases × Creditor-days-target / 365. "
         "Inventory (Raw + WIP + FG) is split 50/20/30 by historical mix "
         "and sized against your Inventory-days-target."),
        ("MPBF (Form V)",
         "Method 1 (Tandon): Min stipulated NWC = 25% of Working Capital "
         "Gap (WCG). MPBF = WCG − Min NWC or WCG − actual NWC, whichever "
         "is lower.  Method 2 (Tandon): Min stipulated NWC = 25% of Total "
         "Current Assets. MPBF = WCG − Min NWC or WCG − actual NWC, "
         "whichever is lower. Banks adopt the LOWER of the two MPBF figures."),
        ("Auditability",
         "Every historical cell in this report can be reconciled row-by-row "
         "against the corresponding Tally report inside your accounting "
         "software. FLOWRA's sync agent stores the full voucher-level trail; "
         "click any figure in the CA Corner tab to drill down to source "
         "vouchers. Projected cells are all formula-driven from the "
         "documented assumptions on this page."),
        ("Regulatory disclosures",
         "This report includes the company's GSTIN, PAN, and MSME "
         "Registration (if provided) on the cover page. These fields are "
         "stored Fernet-AES-128-encrypted in FLOWRA's database; only the "
         "tenant's useradmin (owner role) has access to view or modify "
         "them. Employees, salesmen, dispatch users cannot see or generate "
         "this report."),
    ]


# ─── CMA XLSX builder ────────────────────────────────────────────────────

def build_cma_xlsx(meta: CompanyMeta, hist: List[HistoricalFY],
                    proj: List[HistoricalFY], a: Assumptions) -> bytes:
    """5-sheet Excel workbook (one per Form) — bank submission ready."""
    all_fys = hist + proj
    n_hist = len(hist)
    col_labels = [c.replace("\n", " ") for c in
                   _column_headers_for_fys(all_fys, n_hist)]
    wb = Workbook()

    def _new_sheet(title, labels, rows_by_fy):
        ws = wb.create_sheet(title=title)
        ws.append([meta.company_name])
        ws.append([f"{title}  ·  All figures in Rs. Lacs"])
        ws.append([""] + col_labels)
        # Merge & style header
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill("solid", fgColor="0F1B4C")
        for cell in ws[3]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")
        rows = _transpose_rows(rows_by_fy, labels)
        for r in rows:
            ws.append(r)
        # Set column widths
        ws.column_dimensions["A"].width = 40
        for col in range(2, 2 + len(col_labels)):
            ws.column_dimensions[chr(64 + col)].width = 14
        ws["A1"].font = Font(bold=True, size=13, color="0F1B4C")
        ws["A2"].font = Font(italic=True, size=9, color="475569")
        # Footer row
        ws.append([])
        ws.append([f"{FLOWRA_TAG}  ·  {_now_iso()}  ·  Sheet: {title}"])
        ws.cell(row=ws.max_row, column=1).font = Font(italic=True, size=8,
                                                        color="94A3B8")
        return ws

    # Remove default sheet
    wb.remove(wb["Sheet"])
    _new_sheet("Form II — P&L",
                _form_ii_labels(),
                [_form_ii_rows(fy) for fy in all_fys])
    _new_sheet("Form III — Balance Sheet",
                _form_iii_labels(),
                [_form_iii_rows(fy) for fy in all_fys])
    _new_sheet("Form IV — CA & CL",
                _form_iv_labels(),
                [_form_iv_rows(fy) for fy in all_fys])
    _new_sheet("Form V — MPBF",
                _form_v_labels(),
                [_form_v_rows(fy) for fy in all_fys])
    ff_labels = _funds_flow_labels()
    ff_cols = _funds_flow_deltas(all_fys)
    ff_col_labels = [f"{a1.fy_label}→{b1.fy_label}"
                      for a1, b1 in zip(all_fys[:-1], all_fys[1:])]
    ws6 = wb.create_sheet(title="Form VI — Funds Flow")
    ws6.append([meta.company_name])
    ws6.append(["Funds Flow Statement · All figures in Rs. Lacs"])
    ws6.append([""] + ff_col_labels)
    for cell in ws6[3]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="0F1B4C")
    for r in _transpose_rows(ff_cols, ff_labels):
        ws6.append(r)
    ws6.column_dimensions["A"].width = 42

    # Methodology sheet
    wsm = wb.create_sheet(title="Methodology")
    wsm.append([meta.company_name])
    wsm.append(["How this CMA was generated"])
    wsm.append([])
    for title, body in _methodology_blocks():
        wsm.append([title])
        wsm.cell(row=wsm.max_row, column=1).font = Font(bold=True, size=11,
                                                          color="0F1B4C")
        wsm.append([body])
        wsm.cell(row=wsm.max_row, column=1).alignment = Alignment(
            wrap_text=True, vertical="top")
        wsm.append([])
    wsm.column_dimensions["A"].width = 110
    wsm.append([])
    wsm.append(["Assumptions used"])
    wsm.append(["Sales growth Y1/Y2/Y3 (%)",
                 f"{a.sales_growth_y1} / {a.sales_growth_y2} / "
                 f"{a.sales_growth_y3}"])
    wsm.append(["Debtor days target", a.debtor_days_target])
    wsm.append(["Creditor days target", a.creditor_days_target])
    wsm.append(["Inventory days target", a.inventory_days_target])
    wsm.append(["GP margin target (%)", a.gp_margin_target_pct])
    wsm.append(["Proposed CC/OD limit (₹ Lacs)", a.proposed_cc_limit])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ─── Investor Pitch Deck ─────────────────────────────────────────────────

def build_pitch_pdf(meta: CompanyMeta, hist: List[HistoricalFY],
                     proj: List[HistoricalFY], a: Assumptions,
                     teaser: bool = False) -> bytes:
    """Investor pitch — 16 pages (or 10-page teaser)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=1.4 * cm, rightMargin=1.4 * cm,
        topMargin=1.6 * cm, bottomMargin=1.4 * cm,
        title=f"Pitch Deck — {meta.company_name}",
    )
    story: List[Any] = []
    all_fys = hist + proj
    latest = hist[-1] if hist else None
    ii = compute_form_ii(latest) if latest else {}
    d3 = compute_form_iii(latest) if latest else {}

    # Cover
    story.append(_para(meta.company_name, "h1"))
    subtitle = ("Teaser Deck — Confidential" if teaser
                 else "Investor Pitch Deck — Series A / Growth Capital")
    story.append(_para(subtitle, "small"))
    story.append(Spacer(1, 8))
    story.append(_para(
        "Ready to scale. Backed by verified Tally financials, projected "
        "3 years forward.", "note"))
    story.append(PageBreak())

    # Section 1 — Company snapshot
    story.append(_para("Company Snapshot", "h1"))
    snap = [
        ["Company", meta.company_name],
        ["Sector",
            "Distribution / Trading (verified via Tally Sync)"],
        ["Financial year (latest audited)",
            latest.fy_label if latest else "-"],
        ["Revenue (₹ Lacs)",
            _lakhs(latest.net_sales) if latest else "-"],
        ["EBITDA proxy (Op. Profit before Interest, ₹ Lacs)",
            _lakhs(ii.get("op_profit_bi", 0))],
        ["Net Profit (₹ Lacs)",
            _lakhs(ii.get("npat", 0))],
        ["Net Worth (₹ Lacs)",
            _lakhs(d3.get("nw", 0))],
        ["Current Ratio",
            f"{d3.get('current_ratio', 0):.2f}"],
        ["Ask (proposed working capital, ₹ Lacs)",
            _lakhs(a.proposed_cc_limit)],
    ]
    t = Table(snap, colWidths=[8 * cm, 8.4 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor(SOFT)),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.2, colors.HexColor("#E2E8F0")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(t)
    story.append(PageBreak())

    # Section 2 — Revenue journey
    story.append(_para("Revenue Journey", "h1"))
    rev_rows = [
        ["Year", "Net Sales (₹ Lacs)", "Growth %"],
    ]
    prev = None
    for fy in all_fys:
        g = ((fy.net_sales / prev.net_sales - 1) * 100) if prev and prev.net_sales else 0
        rev_rows.append([fy.fy_label, _lakhs(fy.net_sales),
                          f"{g:+.1f}%" if prev else "-"])
        prev = fy
    story.append(_form_table(rev_rows[1:], [4 * cm, 5 * cm, 4 * cm],
                              rev_rows[0]))
    story.append(Spacer(1, 8))
    story.append(_para(
        "Historical growth is drawn directly from Tally / Busy sales "
        "vouchers. Projected growth reflects the assumptions on the last "
        "page.", "note"))
    story.append(PageBreak())

    # Section 3 — Margin trend
    story.append(_para("Gross & Net Margin Trend", "h1"))
    m_rows = [["Year", "GP % (Est.)", "Net Profit % (After Tax)"]]
    for fy in all_fys:
        dii = compute_form_ii(fy)
        gp = ((fy.net_sales - dii["cost_of_sales"]) / fy.net_sales * 100
                if fy.net_sales else 0)
        np_pct = (dii["npat"] / fy.net_sales * 100
                    if fy.net_sales else 0)
        m_rows.append([fy.fy_label, f"{gp:.2f}%", f"{np_pct:.2f}%"])
    story.append(_form_table(m_rows[1:], [4 * cm, 5 * cm, 5 * cm],
                              m_rows[0]))
    story.append(PageBreak())

    # Section 4 — Balance sheet strength
    story.append(_para("Balance Sheet Strength", "h1"))
    bs_rows = [["Year", "Net Worth (₹ Lacs)", "Current Ratio",
                 "TOL / TNW", "Working Capital (₹ Lacs)"]]
    for fy in all_fys:
        d = compute_form_iii(fy)
        bs_rows.append([fy.fy_label,
                          _lakhs(d["nw"]),
                          f"{d['current_ratio']:.2f}",
                          f"{d['tol_tnw']:.2f}",
                          _lakhs(d["nwc"])])
    story.append(_form_table(bs_rows[1:],
                              [3 * cm, 3.5 * cm, 3 * cm, 2.5 * cm, 4 * cm],
                              bs_rows[0]))
    story.append(PageBreak())

    if teaser:
        # Teaser stops here (10 pages incl. cover + methodology)
        _pitch_methodology(story, a, meta)
        doc.build(story,
                   onFirstPage=_make_canvas_stamper(meta.company_name,
                                                      "Investor Teaser"),
                   onLaterPages=_make_canvas_stamper(meta.company_name,
                                                      "Investor Teaser"))
        return buf.getvalue()

    # Section 5 — Cash flow strength (proxy)
    story.append(_para("Cash Flow Health (Indirect Method)", "h1"))
    cf_rows = [["Year", "PBT (₹ Lacs)", "Depreciation",
                 "Working Capital Change", "Op Cash Flow (proxy)"]]
    for prev, cur in zip(all_fys[:-1], all_fys[1:]):
        pi = compute_form_ii(cur)
        p3 = compute_form_iii(prev)
        c3 = compute_form_iii(cur)
        wc_delta = -((c3["tca"] - p3["tca"])
                       - ((c3["tcl"] - cur.bank_st_borrowings)
                          - (p3["tcl"] - prev.bank_st_borrowings)))
        ocf = pi["pbt"] + cur.depreciation + wc_delta
        cf_rows.append([cur.fy_label, _lakhs(pi["pbt"]),
                          _lakhs(cur.depreciation),
                          _lakhs(wc_delta),
                          _lakhs(ocf)])
    story.append(_form_table(cf_rows[1:],
                              [3 * cm, 3 * cm, 3 * cm, 3.5 * cm, 3.5 * cm],
                              cf_rows[0]))
    story.append(PageBreak())

    # Section 6 — Ratios summary
    story.append(_para("Key Ratios & KPIs", "h1"))
    r_rows = [["Metric", "Latest FY", "Projection Y3"]]
    if all_fys:
        first, last = all_fys[0], all_fys[-1]
        d_first = compute_form_iii(first)
        d_last = compute_form_iii(last)
        i_first = compute_form_ii(first)
        i_last = compute_form_ii(last)
        r_rows.extend([
            ["Net Sales (₹ Lacs)", _lakhs(first.net_sales), _lakhs(last.net_sales)],
            ["GP %",
                _pct(((first.net_sales - i_first["cost_of_sales"])
                        / first.net_sales * 100) if first.net_sales else 0),
                _pct(((last.net_sales - i_last["cost_of_sales"])
                        / last.net_sales * 100) if last.net_sales else 0)],
            ["Current Ratio",
                f"{d_first['current_ratio']:.2f}",
                f"{d_last['current_ratio']:.2f}"],
            ["TOL/TNW",
                f"{d_first['tol_tnw']:.2f}",
                f"{d_last['tol_tnw']:.2f}"],
        ])
    story.append(_form_table(r_rows[1:], [7 * cm, 4 * cm, 4 * cm], r_rows[0]))
    story.append(PageBreak())

    # Section 7 — Use of proceeds
    story.append(_para("Use of Proposed Funds", "h1"))
    up_rows = [
        ["Use", "Amount (₹ Lacs)"],
        ["Working capital cushion (CC/OD)", _lakhs(a.proposed_cc_limit)],
        ["Capex Y1", _lakhs(a.planned_capex_y1)],
        ["Capex Y2", _lakhs(a.planned_capex_y2)],
        ["Capex Y3", _lakhs(a.planned_capex_y3)],
        ["Term loan paydown Y1-Y3",
            _lakhs(a.term_loan_repayment_y1 + a.term_loan_repayment_y2
                    + a.term_loan_repayment_y3)],
    ]
    story.append(_form_table(up_rows[1:], [10 * cm, 5 * cm], up_rows[0]))
    story.append(PageBreak())

    # Sections 8-14 — Placeholders (management commentary, market, risks)
    for title, body in [
        ("Management",
         "Owner-operated, actively engaged in operations. Full financial "
         "transparency via live Tally / Busy sync into FLOWRA."),
        ("Market & Positioning",
         "Existing customer base with proven repeat-purchase behaviour "
         "visible in the receivables ageing on Form IV. Beat-plan-driven "
         "market coverage — quantified in FLOWRA's daily reports."),
        ("Growth Levers",
         "1) Working-capital-led sales expansion (proposed CC limit) "
         "2) Selective capex per Assumptions "
         "3) Debtor-day compression from historical to target."),
        ("Risks & Mitigants",
         "Working-capital cyclicality mitigated by proposed CC facility. "
         "GSTIN / PAN / MSME registration verified. TOL/TNW well within "
         "banker thresholds (see Form III)."),
    ]:
        story.append(_para(title, "h1"))
        story.append(_para(body, "body"))
        story.append(PageBreak())

    _pitch_methodology(story, a, meta)
    doc.build(story,
               onFirstPage=_make_canvas_stamper(meta.company_name,
                                                  "Investor Pitch Deck"),
               onLaterPages=_make_canvas_stamper(meta.company_name,
                                                  "Investor Pitch Deck"))
    return buf.getvalue()


def _pitch_methodology(story: List[Any], a: Assumptions,
                        meta: CompanyMeta) -> None:
    story.append(_para("Methodology & Data Provenance", "h1"))
    for section, body in _methodology_blocks():
        story.append(_para(section, "h2"))
        story.append(_para(body, "body"))
        story.append(Spacer(1, 3))


def build_projections_xlsx(meta: CompanyMeta, hist: List[HistoricalFY],
                            proj: List[HistoricalFY],
                            a: Assumptions) -> bytes:
    """8-sheet XLSX with editable projection scenario (matches PRD promise
    of an 'Excel projections file, editable numbers'."""
    wb = Workbook()
    wb.remove(wb["Sheet"])
    all_fys = hist + proj

    def _sheet_from_field(title, field_name, is_bs=False):
        ws = wb.create_sheet(title=title)
        ws.append([meta.company_name])
        ws.append([title])
        ws.append(["FY"] + [fy.fy_label for fy in all_fys])
        ws.append([field_name] + [getattr(fy, field_name, 0)
                                    for fy in all_fys])
        ws.column_dimensions["A"].width = 30
        ws["A1"].font = Font(bold=True, size=13, color="0F1B4C")
        ws["A2"].font = Font(italic=True, size=10, color="475569")
        return ws

    _sheet_from_field("Revenue", "net_sales")
    _sheet_from_field("Purchases", "purchases")
    _sheet_from_field("SG&A", "sga_expenses")
    _sheet_from_field("Depreciation", "depreciation")

    # Sundry Debtors + Creditors
    ws5 = wb.create_sheet(title="Working Capital")
    ws5.append([meta.company_name])
    ws5.append(["Working Capital Movements"])
    ws5.append(["FY"] + [fy.fy_label for fy in all_fys])
    ws5.append(["Sundry Debtors"] + [fy.receivables_domestic
                                        for fy in all_fys])
    ws5.append(["Sundry Creditors"] + [fy.sundry_creditors
                                          for fy in all_fys])
    ws5.append(["Inventory (Total)"] + [
        fy.inventory_raw + fy.inventory_wip + fy.inventory_finished
        + fy.inventory_spares for fy in all_fys])
    ws5.column_dimensions["A"].width = 22

    # MPBF sheet
    ws6 = wb.create_sheet(title="MPBF")
    ws6.append([meta.company_name])
    ws6.append(["MPBF (Method 1 & Method 2)"])
    ws6.append(["FY"] + [fy.fy_label for fy in all_fys])
    m1 = []
    m2 = []
    for fy in all_fys:
        d = compute_form_iii(fy)
        ocl = d["tcl"] - fy.bank_st_borrowings
        r = compute_form_v_mpbf(fy, ocl, d["nwc"])
        m1.append(r["m1_mpbf"])
        m2.append(r["m2_mpbf"])
    ws6.append(["Method 1 MPBF"] + [round(v, 2) for v in m1])
    ws6.append(["Method 2 MPBF"] + [round(v, 2) for v in m2])
    ws6.column_dimensions["A"].width = 22

    # Assumptions sheet
    ws7 = wb.create_sheet(title="Assumptions")
    ws7.append([meta.company_name])
    ws7.append(["Assumptions (editable — copy this workbook, tweak, "
                 "and re-upload via CA Corner)"])
    for k, v in asdict(a).items():
        ws7.append([k, v])
    ws7.column_dimensions["A"].width = 32
    ws7.column_dimensions["B"].width = 20

    # Methodology sheet
    ws8 = wb.create_sheet(title="Methodology")
    ws8.append([meta.company_name])
    ws8.append([""])
    for title, body in _methodology_blocks():
        ws8.append([title])
        ws8.cell(row=ws8.max_row, column=1).font = Font(bold=True,
                                                          color="0F1B4C")
        ws8.append([body])
        ws8.cell(row=ws8.max_row, column=1).alignment = Alignment(
            wrap_text=True, vertical="top")
        ws8.append([])
    ws8.column_dimensions["A"].width = 110

    # Footer stamp on every sheet
    for ws in wb.worksheets:
        ws.append([])
        ws.append([f"{FLOWRA_TAG}  ·  {_now_iso()}"])
        ws.cell(row=ws.max_row, column=1).font = Font(italic=True, size=8,
                                                        color="94A3B8")

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
